def error(msg):
	print("error! >", msg)
	exit(-1)